package org.tbcc.entity;

/**
 * TbccImageControls generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public class TbccImageControls implements java.io.Serializable {

	// Fields

	private Long id;
	//private TbccProjectImages tbccProjectImages;
	private String projectId;
	private long imageId;
	private Integer netid;
	private Integer refid;
	private Integer dataType;
	private Integer portNo;
	private String titleMsg;
	private String tipMsg;
	private String unitMsg;
	private Integer cleft;
	private Integer ctop;
	private Integer cwidth;
	private Integer cheight;

	// Constructors

	/** default constructor */
	public TbccImageControls() {
	}

	/** minimal constructor */
	public TbccImageControls(//TbccProjectImages tbccProjectImages,
			String projectId, long imageId, Integer netid, Integer refid,
			Integer portNo, Integer cleft) {
		//this.tbccProjectImages = tbccProjectImages;
		this.projectId = projectId;
		this.imageId = imageId;
		this.netid = netid;
		this.refid = refid;
		this.portNo = portNo;
		this.cleft = cleft;
	}

	/** full constructor */
	public TbccImageControls(//TbccProjectImages tbccProjectImages,
			String projectId, long imageId, Integer netid, Integer refid,
			Integer portNo, String titleMsg, String tipMsg, String unitMsg,
			Integer cleft, Integer ctop, Integer cwidth, Integer cheight) {
		//this.tbccProjectImages = tbccProjectImages;
		this.projectId = projectId;
		this.imageId = imageId;
		this.netid = netid;
		this.refid = refid;
		this.portNo = portNo;
		this.titleMsg = titleMsg;
		this.tipMsg = tipMsg;
		this.unitMsg = unitMsg;
		this.cleft = cleft;
		this.ctop = ctop;
		this.cwidth = cwidth;
		this.cheight = cheight;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

//	public TbccProjectImages getTbccProjectImages() {
//		return this.tbccProjectImages;
//	}
//
//	public void setTbccProjectImages(TbccProjectImages tbccProjectImages) {
//		this.tbccProjectImages = tbccProjectImages;
//	}

	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	public long getImageId() {
		return this.imageId;
	}

	public void setImageId(long imageId) {
		this.imageId = imageId;
	}

	public Integer getNetid() {
		return this.netid;
	}

	public void setNetid(Integer netid) {
		this.netid = netid;
	}

	public Integer getRefid() {
		return this.refid;
	}

	public void setRefid(Integer refid) {
		this.refid = refid;
	}

	public Integer getPortNo() {
		return this.portNo;
	}

	public void setPortNo(Integer portNo) {
		this.portNo = portNo;
	}

	public String getTitleMsg() {
		return this.titleMsg;
	}

	public void setTitleMsg(String titleMsg) {
		this.titleMsg = titleMsg;
	}

	public String getTipMsg() {
		return this.tipMsg;
	}

	public void setTipMsg(String tipMsg) {
		this.tipMsg = tipMsg;
	}

	public String getUnitMsg() {
		return this.unitMsg;
	}

	public void setUnitMsg(String unitMsg) {
		this.unitMsg = unitMsg;
	}

	public Integer getCleft() {
		return this.cleft;
	}

	public void setCleft(Integer cleft) {
		this.cleft = cleft;
	}

	public Integer getCtop() {
		return this.ctop;
	}

	public void setCtop(Integer ctop) {
		this.ctop = ctop;
	}

	public Integer getCwidth() {
		return this.cwidth;
	}

	public void setCwidth(Integer cwidth) {
		this.cwidth = cwidth;
	}

	public Integer getCheight() {
		return this.cheight;
	}

	public void setCheight(Integer cheight) {
		this.cheight = cheight;
	}

	public Integer getDataType() {
		return dataType;
	}

	public void setDataType(Integer dataType) {
		this.dataType = dataType;
	}

}